<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IndikatorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $indikators = [
            // Sub Kategori 1: I. PEMENUHAN - 1. MANAJEMEN PERUBAHAN
            [
                'sub_kategori_id' => 1,
                'kode' => 'i',
                'nama' => 'Penyusunan Tim Kerja',
                'bobot' => 0.50,
                'deskripsi' => null,
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 1,
                'kode' => 'ii',
                'nama' => 'Rencana Pembangunan Zona Integritas',
                'bobot' => 1.00,
                'deskripsi' => null,
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 1,
                'kode' => 'iii',
                'nama' => 'Pemantauan dan Evaluasi Pembangunan WBK/WBBM',
                'bobot' => 1.00,
                'deskripsi' => null,
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 1,
                'kode' => 'iv',
                'nama' => 'Perubahan pola pikir dan budaya kerja',
                'bobot' => 1.50,
                'deskripsi' => null,
                'urutan' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sub Kategori 2: I. PEMENUHAN - 2. PENATAAN TATALAKSANA
            [
                'sub_kategori_id' => 2,
                'kode' => 'i',
                'nama' => 'Prosedur Operasional Tetap (SOP) Kegiatan Utama',
                'bobot' => 1.00,
                'deskripsi' => null,
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 2,
                'kode' => 'ii',
                'nama' => 'Sistem Pemerintahan Berbasis Elektronik (SPBE)',
                'bobot' => 2.00,
                'deskripsi' => null,
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 2,
                'kode' => 'iii',
                'nama' => 'Keterbukaan Informasi Publik',
                'bobot' => 0.50,
                'deskripsi' => null,
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sub Kategori 3: I. PEMENUHAN - 3. PENATAAN SISTEM MANAJEMEN SDM APARATUR
            [
                'sub_kategori_id' => 3,
                'kode' => 'i',
                'nama' => 'Perencanaan Kebutuhan Pegawai sesuai dengan Kebutuhan Organisasi',
                'bobot' => 0.25,
                'deskripsi' => null,
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 3,
                'kode' => 'ii',
                'nama' => 'Pola Mutasi Internal',
                'bobot' => 0.50,
                'deskripsi' => null,
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 3,
                'kode' => 'iii',
                'nama' => 'Pengembangan Pegawai Berbasis Kompetensi',
                'bobot' => 1.25,
                'deskripsi' => null,
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 3,
                'kode' => 'iv',
                'nama' => 'Penetapan Kinerja Individu',
                'bobot' => 2.00,
                'deskripsi' => null,
                'urutan' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 3,
                'kode' => 'v',
                'nama' => 'Penegakan Aturan Disiplin/Kode Etik/Kode Perilaku Pegawai',
                'bobot' => 0.75,
                'deskripsi' => null,
                'urutan' => 5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 3,
                'kode' => 'vi',
                'nama' => 'Sistem Informasi Kepegawaian',
                'bobot' => 0.25,
                'deskripsi' => null,
                'urutan' => 6,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sub Kategori 4: I. PEMENUHAN - 4. PENGUATAN AKUNTABILITAS
            [
                'sub_kategori_id' => 4,
                'kode' => 'i',
                'nama' => 'Keterlibatan Pimpinan',
                'bobot' => 2.50,
                'deskripsi' => null,
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 4,
                'kode' => 'ii',
                'nama' => 'Pengelolaan Akuntabilitas Kinerja',
                'bobot' => 2.50,
                'deskripsi' => null,
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sub Kategori 5: I. PEMENUHAN - 5. PENGUATAN PENGAWASAN
            [
                'sub_kategori_id' => 5,
                'kode' => 'i',
                'nama' => 'Pengendalian Gratifikasi',
                'bobot' => 1.50,
                'deskripsi' => null,
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 5,
                'kode' => 'ii',
                'nama' => 'Penerapan Sistem Pengendalian Intern Pemerintah (SPIP)',
                'bobot' => 1.50,
                'deskripsi' => null,
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 5,
                'kode' => 'iii',
                'nama' => 'Pengaduan Masyarakat',
                'bobot' => 1.50,
                'deskripsi' => null,
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 5,
                'kode' => 'iv',
                'nama' => 'Whistle-Blowing System',
                'bobot' => 1.50,
                'deskripsi' => null,
                'urutan' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 5,
                'kode' => 'v',
                'nama' => 'Penanganan Benturan Kepentingan',
                'bobot' => 1.50,
                'deskripsi' => null,
                'urutan' => 5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sub Kategori 6: I. PEMENUHAN - 6. PENINGKATAN KUALITAS PELAYANAN PUBLIK
            [
                'sub_kategori_id' => 6,
                'kode' => 'i',
                'nama' => 'Standar Pelayanan',
                'bobot' => 1.00,
                'deskripsi' => null,
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 6,
                'kode' => 'ii',
                'nama' => 'Budaya Pelayanan Prima',
                'bobot' => 1.00,
                'deskripsi' => null,
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 6,
                'kode' => 'iii',
                'nama' => 'Pengelolaan Pengaduan',
                'bobot' => 1.00,
                'deskripsi' => null,
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 6,
                'kode' => 'iv',
                'nama' => 'Penilaian Kepuasan terhadap Pelayanan',
                'bobot' => 1.00,
                'deskripsi' => null,
                'urutan' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 6,
                'kode' => 'v',
                'nama' => 'Pemanfaatan Teknologi Informasi',
                'bobot' => 1.00,
                'deskripsi' => null,
                'urutan' => 5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sub Kategori 7: II. REFORM - 1. MANAJEMEN PERUBAHAN
            [
                'sub_kategori_id' => 7,
                'kode' => 'i',
                'nama' => 'Komitmen dalam perubahan',
                'bobot' => 2.00,
                'deskripsi' => null,
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 7,
                'kode' => 'ii',
                'nama' => 'Komitmen Pimpinan',
                'bobot' => 1.00,
                'deskripsi' => null,
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 7,
                'kode' => 'iii',
                'nama' => 'Membangun Budaya Kerja',
                'bobot' => 1.00,
                'deskripsi' => null,
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sub Kategori 8: II. REFORM - 2. PENATAAN TATALAKSANA
            [
                'sub_kategori_id' => 8,
                'kode' => 'i',
                'nama' => 'Peta Proses Bisnis Mempengaruhi Penyederhanaan Jabatan',
                'bobot' => 0.50,
                'deskripsi' => null,
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 8,
                'kode' => 'ii',
                'nama' => 'Sistem Pemerintahan Berbasis Elektronik (SPBE) yang Terintegrasi',
                'bobot' => 1.00,
                'deskripsi' => null,
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 8,
                'kode' => 'iii',
                'nama' => 'Transformasi Digital Memberikan Nilai Manfaat',
                'bobot' => 2.00,
                'deskripsi' => null,
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sub Kategori 9: II. REFORM - 3. PENATAAN SISTEM MANAJEMEN SDM APARATUR
            [
                'sub_kategori_id' => 9,
                'kode' => 'i',
                'nama' => 'Kinerja Individu',
                'bobot' => 1.50,
                'deskripsi' => null,
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 9,
                'kode' => 'ii',
                'nama' => 'Assessment Pegawai',
                'bobot' => 1.50,
                'deskripsi' => null,
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 9,
                'kode' => 'iii',
                'nama' => 'Pelanggaran Disiplin Pegawai',
                'bobot' => 2.00,
                'deskripsi' => null,
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sub Kategori 10: II. REFORM - 4. PENGUATAN AKUNTABILITAS
            [
                'sub_kategori_id' => 10,
                'kode' => 'i',
                'nama' => 'Meningkatnya capaian kinerja unit kerja',
                'bobot' => 2.00,
                'deskripsi' => null,
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 10,
                'kode' => 'ii',
                'nama' => 'Pemberian Reward and Punishment',
                'bobot' => 1.50,
                'deskripsi' => null,
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 10,
                'kode' => 'iii',
                'nama' => 'Kerangka Logis Kinerja',
                'bobot' => 1.50,
                'deskripsi' => null,
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sub Kategori 11: II. REFORM - 5. PENGUATAN PENGAWASAN
            [
                'sub_kategori_id' => 11,
                'kode' => 'i',
                'nama' => 'Mekanisme Pengendalian',
                'bobot' => 2.50,
                'deskripsi' => null,
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 11,
                'kode' => 'ii',
                'nama' => 'Penanganan Pengaduan Masyarakat',
                'bobot' => 3.00,
                'deskripsi' => null,
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 11,
                'kode' => 'iii',
                'nama' => 'Penyampaian Laporan Harta Kekayaan',
                'bobot' => 2.00,
                'deskripsi' => null,
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sub Kategori 12: II. REFORM - 6. PENINGKATAN KUALITAS PELAYANAN PUBLIK
            [
                'sub_kategori_id' => 12,
                'kode' => 'i',
                'nama' => 'Upaya dan/atau Inovasi Pelayanan Publik',
                'bobot' => 2.50,
                'deskripsi' => null,
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_kategori_id' => 12,
                'kode' => 'ii',
                'nama' => 'Penanganan Pengaduan Pelayanan dan Konsultasi',
                'bobot' => 2.50,
                'deskripsi' => null,
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('tm_indikator')->insert($indikators);
    }
}
