<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PertanyaanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Hapus data lama terlebih dahulu dengan disable foreign key check
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('tm_pertanyaan')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $pertanyaans = [
            // Indikator 1: Penyusunan Tim Kerja
            [
                'indikator_id' => 1,
                'kode' => 'a',
                'pertanyaan' => 'Unit kerja telah membentuk tim untuk melakukan pembangunan Zona Integritas',
                'penjelasan' => 'Ya, jika Tim telah dibentuk di dalam unit kerja.',
                'tipe_jawaban' => 'ya_tidak',
                'pilihan_jawaban' => json_encode(['Ya', 'Tidak']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 1,
                'kode' => 'b',
                'pertanyaan' => 'Penentuan anggota Tim dipilih melalui prosedur/mekanisme yang jelas',
                'penjelasan' => 'a. Jika dengan prosedur/mekanisme yang jelas dan mewakili seluruh unsur dalam unit kerja b. Jika sebagian menggunakan prosedur yang mewakili sebagian besar unsur dalam unit kerja c. Jika tidak di seleksi.',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 2: Rencana Pembangunan Zona Integritas
            [
                'indikator_id' => 2,
                'kode' => 'a',
                'pertanyaan' => 'Terdapat dokumen rencana kerja pembangunan Zona Integritas menuju WBK/WBBM',
                'penjelasan' => 'Ya, jika memiliki rencana kerja pembangunan Zona Integritas.',
                'tipe_jawaban' => 'ya_tidak',
                'pilihan_jawaban' => json_encode(['Ya', 'Tidak']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 2,
                'kode' => 'b',
                'pertanyaan' => 'Dalam dokumen pembangunan terdapat target-target prioritas yang relevan dengan tujuan pembangunan WBK/WBBM',
                'penjelasan' => 'a. Jika semua target-target prioritas relevan dengan tujuanpembangunan WBK/WBBM b. Jika sebagian target-target prioritas relevan dengan tujuan pembangunan WBK/WBBM c. Jika tidak ada target-target prioritas yang relevan dengan tujuan pembangunan WBK/WBBM',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 2,
                'kode' => 'c',
                'pertanyaan' => 'Terdapat mekanisme atau media untuk mensosialisasikan pembangunan WBK/WBBM',
                'penjelasan' => 'a. Jika telah dilakukan pengelolaan media/aktivitas interaktif yang efektif untuk menginformasikan pembangunan ZI kepada internal dan stakeholder secara berkala b. Jika pengelolaan media/aktivitas interaktif dilakukan secara terbatas dan tidak secara berkala c. Jika pengelolaan media/aktivitas interaktif belum dilakukan',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 3: Pemantauan dan Evaluasi Pembangunan WBK/WBBM
            [
                'indikator_id' => 3,
                'kode' => 'a',
                'pertanyaan' => 'Seluruh kegiatan pembangunan sudah dilaksanakan sesuai dengan rencana',
                'penjelasan' => 'a. Jika semua kegiatan pembangunan telah dilaksanakan sesuai dengan rencana b. Jika sebagian besar kegiatan pembangunan telah dilaksanakan sesuai dengan rencana c. Jika sebagian kecil kegiatan pembangunan telah dilaksanakan sesuai dengan rencana d. Jika belum ada kegiatan pembangunan yang dilakukan sesuai dengan rencana',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 3,
                'kode' => 'b',
                'pertanyaan' => 'Terdapat monitoring dan evaluasi terhadap pembangunan Zona Integritas',
                'penjelasan' => 'a. Jika monitoring dan evaluasi melibatkan pimpinan dan dilakukan secara berkala b. Jika monitoring dan evaluasi melibatkan pimpinan tetapi tidak secara berkala c. Jika monitoring dan evaluasi tidak melibatkan pimpinan dan tidak secara berkala d. Jika tidak terdapat monitoring dan evaluasi terhadap pembangunan zona integritas',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 3,
                'kode' => 'c',
                'pertanyaan' => 'Hasil Monitoring dan Evaluasi telah ditindaklanjuti',
                'penjelasan' => 'a. Jika semua catatan/rekomendasi hasil monitoring dan evaluasi tim internal atas persiapan dan pelaksanaan kegiatan Unit WBK/WBBM telah ditindaklanjuti b. Jika sebagian besar catatan/rekomendasi hasil monitoring danevaluasi tim internal atas persiapan dan pelaksanaan kegiatanUnit WBK/WBBM telah ditindaklanjuti c. Jika sebagian kecil catatan/rekomendasi hasil monitoring dan evaluasi tim internal atas persiapan dan pelaksanaan kegiatan Unit WBK/WBBM telah ditindaklanjuti d. Jika catatan/rekomendasi hasil monitoring dan evaluasi tim internal atas persiapan dan pelaksanaan kegiatan Unit WBK/WBBM belum ditindaklanjuti',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 4: Perubahan pola pikir dan budaya kerja
            [
                'indikator_id' => 4,
                'kode' => 'a',
                'pertanyaan' => 'Pimpinan berperan sebagai role model dalam pelaksanaan Pembangunan WBK/WBBM',
                'penjelasan' => 'ya, jika pimpinan menjadi contoh pelaksanaan nilai-nilai organisasi.',
                'tipe_jawaban' => 'ya_tidak',
                'pilihan_jawaban' => json_encode(['Ya', 'Tidak']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 4,
                'kode' => 'b',
                'pertanyaan' => 'Sudah ditetapkan agen perubahan',
                'penjelasan' => 'a. Jika agen perubahan telah ditetapkan dan berkontribusi terhadap perubahan pada unit kerjanya b. Jika agen perubahan telah ditetapkan namun belum berkontribusi terhadap perubahan pada unit kerjanya c. Jika belum terdapat agen perubahan',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 4,
                'kode' => 'c',
                'pertanyaan' => 'Telah dibangun budaya kerja dan pola pikir di lingkungan organisasi',
                'penjelasan' => 'a. Jika telah dilakukan upaya pembangunan budaya kerja dan pola pikir dan mampu mengurangi resistensi atas perubahan b. Jika telah dilakukan upaya pembangunan budaya kerja dan pola pikir tapi masih terdapat resistensi atas perubahan c. Jika belum terdapat upaya pembangunan budaya kerja dan pola pikir',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 4,
                'kode' => 'd',
                'pertanyaan' => 'Anggota organisasi terlibat dalam pembangunan Zona Integritas menuju WBK/WBBM',
                'penjelasan' => 'a. Jika semua anggota terlibat dalam pembangunan Zona Integritas menuju WBK/WBBM dan usulan-usulan dari anggota diakomodasikan dalam keputusan b. Jika sebagian besar anggota terlibat dalam pembangunan Zona Integritas menuju WBK/WBBM c. Jika sebagian kecil anggota terlibat dalam pembangunan Zona Integritas menuju WBK/WBBM d. Jika belum ada anggota terlibat dalam pembangunan Zona Integritas menuju WBK/WBBM',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 5: Prosedur Operasional Tetap (SOP) Kegiatan Utama
            [
                'indikator_id' => 5,
                'kode' => 'a',
                'pertanyaan' => 'SOP mengacu pada peta proses bisnis instansi',
                'penjelasan' => 'a. Jika semua SOP unit telah mengacu peta proses bisnis dan juga melakukan inovasi yang selaras b. Jika semua SOP unit telah mengacu peta proses bisnis c. Jika sebagian SOP unit telah mengacu peta proses bisnis d. Jika belum terdapat SOP unit yang mengacu peta proses bisnis',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 5,
                'kode' => 'b',
                'pertanyaan' => 'Prosedur operasional tetap (SOP) telah diterapkan',
                'penjelasan' => 'a. Jika unit telah menerapkan seluruh SOP yang ditetapkan organisasi dan juga melakukan inovasi pada SOP yang diterapkan b. Jika unit telah menerapkan seluruh SOP yang ditetapkan organisasi c. Jika unit telah menerapkan sebagian besar SOP yang ditetapkan organisasi d. Jika unit telah menerapkan sebagian kecil SOP yang ditetapkan organisasi e. Jika unit belum menerapkan SOP yang telah ditetapkan organisasi',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D', 'E']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 5,
                'kode' => 'c',
                'pertanyaan' => 'Prosedur operasional tetap (SOP) telah dievaluasi',
                'penjelasan' => 'a. Jika seluruh SOP utama telah dievaluasi dan telah ditindaklanjuti berupa perbaikan SOP atau usulan perbaikan SOP b. Jika sebagian besar SOP utama telah dievaluasi dan telah ditindaklanjuti berupa perbaikan SOP atau usulan perbaikan SOP c. Jika sebagian besar SOP utama telah dievaluasi tetapi belum ditindaklanjuti d. Jika sebagian kecil SOP utama telah dievaluasi e. Jika SOP belum pernah dievaluasi',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D', 'E']),
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 6: Sistem Pemerintahan Berbasis Elektronik (SPBE)
            [
                'indikator_id' => 6,
                'kode' => 'a',
                'pertanyaan' => 'Sistem pengukuran kinerja unit sudah menggunakan teknologi informasi',
                'penjelasan' => 'a. Jika unit memiliki sistem pengukuran kinerja (e-performance/e-sakip) yang menggunakan teknologi informasi dan juga melakukan inovasi b. Jika unit memiliki sistem pengukuran kinerja (e-performance/e-sakip) yang menggunakan teknologi informasi c. Jika belum memiliki sistem pengukuran kinerja (e-performance/e-sakip) yang menggunakan teknologi informasi',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 6,
                'kode' => 'b',
                'pertanyaan' => 'Operasionalisasi manajemen SDM sudah menggunakan teknologi informasi',
                'penjelasan' => 'a. Jika unit memiliki operasionalisasi manajemen SDM yang menggunakan teknologi informasi dan juga melakukan inovasi b. Jika unit memiliki operasionalisasi manajemen SDM yang menggunakan teknologi informasi secara terpusat c. Jika belum menggunakan teknologi informasi dalam operasionalisasi manajemen SDM',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 6,
                'kode' => 'c',
                'pertanyaan' => 'Pemberian pelayanan kepada publik sudah menggunakan teknologi informasi',
                'penjelasan' => 'a. Jika unit memberikan pelayanan kepada publik dengan menggunakan teknologi informasi terpusat/unit sendiri dan terdapat inovasi b. Jika unit memberikan pelayanan kepada publik dengan menggunakan teknologi informasi secara terpusat c. Jika belum memberikan pelayanan kepada publik dengan menggunakan teknologi informasi',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 6,
                'kode' => 'd',
                'pertanyaan' => 'Telah dilakukan monitoring dan dan evaluasi terhadap pemanfaatan teknologi informasi dalam pengukuran kinerja unit, operasionalisasi SDM, dan pemberian layanan kepada publik',
                'penjelasan' => 'a. Jika laporan monitoring dan evaluasi terhadap pemanfaatan teknologi informasi dalam pengukuran kinerja unit, operasionalisasi SDM, dan pemberian layanan kepada publik sudah dilakukan secara berkala b. Jika laporan monitoring dan evaluasi terhadap pemanfaatan teknologi informasi dalam pengukuran kinerja unit, operasionalisasi SDM, dan pemberian layanan kepada publik sudah dilakukan tetapi tidak secara berkala c. Jika tidak terdapat monitoring dan evaluasi terhadap pemanfaatan teknologi informasi dalam pengukuran kinerja unit, operasionalisasi SDM, dan pemberian layanan kepada publik',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 7: Keterbukaan Informasi Publik
            [
                'indikator_id' => 7,
                'kode' => 'a',
                'pertanyaan' => 'Kebijakan tentang keterbukaan informasi publik telah diterapkan',
                'penjelasan' => 'a. Jika sudah terdapat Pejabat Pengelola Informasi Publik (PPID) yang menyebarkan seluruh informasi yang dapat diakses secara mutakhir dan lengkap b. Jika sudah terdapat PPID yang menyebarkan sebagian informasi yang dapat diakses secara mutakhir dan lengkap c. Jika belum ada PPID dan belum melakukan penyebaran informasi publik',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 7,
                'kode' => 'b',
                'pertanyaan' => 'Telah dilakukan monitoring dan evaluasi pelaksanaan kebijakan keterbukaan informasi publik',
                'penjelasan' => 'a. Jika dilakukan monitoring dan evaluasi pelaksanaan kebijakan keterbukaan informasi publik dan telah ditindaklanjuti b. Jika monitoring dan evaluasi pelaksanaan kebijakan keterbukaan informasi publik telah dilakukan tetapi belum ditindaklanjuti c. Jika monitoring dan evaluasi pelaksanaan kebijakan keterbukaan informasi publik belum dilakukan',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 8: Perencanaan Kebutuhan Pegawai sesuai dengan Kebutuhan Organisasi
            [
                'indikator_id' => 8,
                'kode' => 'a',
                'pertanyaan' => 'Kebutuhan pegawai yang disusun oleh unit kerja mengacu kepada peta jabatan dan hasil analisis beban kerja',
                'penjelasan' => 'Ya, jika kebutuhan pegawai yang disusun oleh unit kerja mengacu kepada peta jabatan dan hasil analisis beban kerja.',
                'tipe_jawaban' => 'ya_tidak',
                'pilihan_jawaban' => json_encode(['Ya', 'Tidak']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 8,
                'kode' => 'b',
                'pertanyaan' => 'Penempatan pegawai hasil rekrutmen murni mengacu kepada kebutuhan pegawai yang telah disusun per jabatan',
                'penjelasan' => 'a. Jika semua penempatan pegawai hasil rekrutmen murni mengacu kepada kebutuhan pegawai yang telah disusun per jabatan b. Jika sebagian besar penempatan pegawai hasil rekrutmen murni mengacu kepada kebutuhan pegawai yang telah disusun per jabatan c. Jika sebagian kecil penempatan pegawai hasil rekrutmen murni mengacu kepada kebutuhan pegawai yang telah disusun per jabatan d. Jika penempatan pegawai hasil rekrutmen murni tidak mengacu kepada kebutuhan pegawai yang telah disusun per jabatan',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 8,
                'kode' => 'c',
                'pertanyaan' => 'Telah dilakukan monitoring dan dan evaluasi terhadap penempatan pegawai rekrutmen untuk memenuhi kebutuhan jabatan',
                'penjelasan' => 'Ya, jika sudah dilakukan monitoring dan evaluasi terhadap penempatan pegawai hasil rekrutmen untuk memenuhi kebutuhan jabatan.',
                'tipe_jawaban' => 'ya_tidak',
                'pilihan_jawaban' => json_encode(['Ya', 'Tidak']),
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 9: Pola Mutasi Internal
            [
                'indikator_id' => 9,
                'kode' => 'a',
                'pertanyaan' => 'Dalam melakukan pengembangan karier pegawai, telah dilakukan mutasi pegawai antar jabatan',
                'penjelasan' => 'Ya, jika dilakukan mutasi pegawai antar jabatan sebagai wujud dari pengembangan karier pegawai.',
                'tipe_jawaban' => 'ya_tidak',
                'pilihan_jawaban' => json_encode(['Ya', 'Tidak']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 9,
                'kode' => 'b',
                'pertanyaan' => 'Dalam melakukan mutasi pegawai antar jabatan telah memperhatikan kompetensi jabatan dan mengikuti pola mutasi yang telah ditetapkan',
                'penjelasan' => 'a. Jika semua mutasi pegawai antar jabatan telah memperhatikan kompetensi jabatan dan mengikuti pola mutasi yang telah ditetapkan organisasi dan juga unit kerja memberikan pertimbangan terkait hal ini b. Jika semua mutasi pegawai antar jabatan telah memperhatikan kompetensi jabatan dan mengikuti pola mutasi yang telah ditetapkan organisasi c. Jika sebagian besar mutasi pegawai antar jabatan telah memperhatikan kompetensi jabatan dan mengikuti pola mutasi yang telah ditetapkan organisasi d. Jika sebagian kecil semua mutasi pegawai antar jabatan telah memperhatikan kompetensi jabatan dan mengikuti pola mutasi yang telah ditetapkan organisasi e. Jika mutasi pegawai antar jabatan belum memperhatikan kompetensi jabatan dan mengikuti pola mutasi yang telah ditetapkan organisasi',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D', 'E']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 9,
                'kode' => 'c',
                'pertanyaan' => 'Telah dilakukan monitoring dan evaluasi terhadap kegiatan mutasi yang telah dilakukan dalam kaitannya dengan perbaikan kinerja',
                'penjelasan' => 'Ya, jika sudah dilakukan monitoring dan evaluasi terhadap kegiatan mutasi yang telah dilakukan dalam kaitannya dengan perbaikan kinerja.',
                'tipe_jawaban' => 'ya_tidak',
                'pilihan_jawaban' => json_encode(['Ya', 'Tidak']),
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 10: Pengembangan Pegawai Berbasis Kompetensi
            [
                'indikator_id' => 10,
                'kode' => 'a',
                'pertanyaan' => 'Unit Kerja melakukan Training Need Analysis Untuk pengembangan kompetensi',
                'penjelasan' => 'Ya, jika sudah dilakukan Training Need Analysis Untuk pengembangan kompetensi.',
                'tipe_jawaban' => 'ya_tidak',
                'pilihan_jawaban' => json_encode(['Ya', 'Tidak']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 10,
                'kode' => 'b',
                'pertanyaan' => 'Dalam menyusun rencana pengembangan kompetensi pegawai, telah mempertimbangkan hasil pengelolaan kinerja pegawai',
                'penjelasan' => 'a. Jika semua rencana pengembangan kompetensi pegawai mempertimbangkan hasil pengelolaan kinerja pegawai b. Jika sebagian besar rencana pengembangan kompetensi pegawai mempertimbangkan hasil pengelolaan kinerja pegawai c. Jika sebagian kecil rencana pengembangan kompetensi pegawai mempertimbangkan hasil pengelolaan kinerja pegawai d. Jika belum ada rencana pengembangan kompetensi pegawai yang mempertimbangkan hasil pengelolaan kinerja pegawai',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 10,
                'kode' => 'c',
                'pertanyaan' => 'Tingkat kesenjangan kompetensi pegawai yang ada dengan standar kompetensi yang ditetapkan untuk masing-masing jabatan',
                'penjelasan' => 'a. Jika persentase kesenjangan kompetensi pegawai dengan standar kompetensi yang ditetapkan sebesar <25% b. Jika persentase kesenjangan kompetensi pegawai dengan standar kompetensi yang ditetapkan sebesar >25%-50% c. Jika sebagian besar kompetensi pegawai dengan standar kompetensi yang ditetapkan untuk masing-masing jabatan >50% -75% d. Jika persentase kesenjangan kompetensi pegawai dengan standar kompetensi yang ditetapkan sebesar >75%-100%',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 10,
                'kode' => 'd',
                'pertanyaan' => 'Pegawai di Unit Kerja telah memperoleh kesempatan/hak untuk mengikuti diklat maupun pengembangan kompetensi lainnya',
                'penjelasan' => 'a. Jika seluruh pegawai di Unit Kerja telah memperoleh kesempatan/hak untuk mengikuti diklat maupun pengembangan kompetensi lainnya b. Jika sebagian besar pegawai di Unit Kerja telah memperoleh kesempatan/hak untuk mengikuti diklat maupun pengembangan kompetensi lainnya c. Jika sebagian kecil pegawai di Unit Kerja telah memperoleh kesempatan/hak untuk mengikuti diklat maupun pengembangan kompetensi lainnya d. Jika belum ada pegawai di Unit Kerja telah memperoleh kesempatan/hak untuk mengikuti diklat maupun pengembangan kompetensi lainnya',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 10,
                'kode' => 'e',
                'pertanyaan' => 'Dalam pelaksanaan pengembangan kompetensi, unit kerja melakukan upaya pengembangan kompetensi kepada pegawai (seperti pengikutsertaan pada lembaga pelatihan, in-house training, coaching, atau mentoring)',
                'penjelasan' => 'a. Jika unit kerja melakukan upaya pengembangan kompetensi kepada seluruh pegawai b. Jika unit kerja melakukan upaya pengembangan kompetensi kepada sebagian besar pegawai c. Jika unit kerja melakukan upaya pengembangan kompetensi kepada sebagian kecil pegawai d. Jika unit kerja belum melakukan upaya pengembangan kompetensi kepada pegawai',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 10,
                'kode' => 'f',
                'pertanyaan' => 'Telah dilakukan monitoring dan evaluasi terhadap hasil pengembangan kompetensi dalam kaitannya dengan perbaikan kinerja',
                'penjelasan' => 'a. Jika monitoring dan evaluasi terhadap hasil pengembangan kompetensi dalam kaitannya dengan perbaikan kinerja telah dilakukan secara berkala b. Jika monitoring dan evaluasi terhadap hasil pengembangan kompetensi dalam kaitannya dengan perbaikan kinerja telah dilakukan namun tidak secara berkala c. Jika monitoring dan evaluasi terhadap hasil pengembangan kompetensi dalam kaitannya dengan perbaikan kinerja belum dilakukan',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 6,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 11: Penetapan Kinerja Individu
            [
                'indikator_id' => 11,
                'kode' => 'a',
                'pertanyaan' => 'Terdapat penetapan kinerja individu yang terkait dengan perjanjian kinerja organisasi',
                'penjelasan' => 'a. Jika seluruh penetapan kinerja individu terkait dengan kinerja organisasi serta perjanjian kinerja selaras dengan sasaran kinerja pegawai (SKP) b. Jika sebagian besar penetapan kinerja individu terkait dengan kinerja organisasi c. Jika sebagian kecil penetapan kinerja individu terkait dengan kinerja organisasi d. Jika belum ada penetapan kinerja individu terkait dengan kinerja organisasi',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 11,
                'kode' => 'b',
                'pertanyaan' => 'Ukuran kinerja individu telah memiliki kesesuaian dengan indikator kinerja individu level diatasnya',
                'penjelasan' => 'a. Jika seluruh ukuran kinerja individu telah memiliki kesesuaian dengan indikator kinerja individu level diatasnya serta menggambarkan logic model b. Jika sebagian besar ukuran kinerja individu telah memiliki kesesuaian dengan indikator kinerja individu level diatasnya c. Jika sebagian kecil ukuran kinerja individu telah memiliki kesesuaian dengan indikator kinerja individu level diatasnya d. Jika ukuran kinerja individu belum memiliki kesesuaian dengan indikator kinerja individu level diatasnya',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 11,
                'kode' => 'c',
                'pertanyaan' => 'Pengukuran kinerja individu dilakukan secara periodik',
                'penjelasan' => 'a. Jika pengukuran kinerja individu dilakukan secara bulanan b. Jika pengukuran kinerja individu dilakukan secara triwulanan c. Jika pengukuran kinerja individu dilakukan secara semesteran d. Jika pengukuran kinerja individu dilakukan secara tahunan e. Jika pengukuran kinerja individu belum dilakukan',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D', 'E']),
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 11,
                'kode' => 'd',
                'pertanyaan' => 'Hasil penilaian kinerja individu telah dijadikan dasar untuk pemberian reward',
                'penjelasan' => 'Ya, jika hasil hasil penilaian kinerja individu telah dijadikan dasar untuk pemberian reward (Seperti: pengembangan karir individu, atau penghargaan)',
                'tipe_jawaban' => 'ya_tidak',
                'pilihan_jawaban' => json_encode(['Ya', 'Tidak']),
                'urutan' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 12: Penegakan Aturan Disiplin/Kode Etik/Kode Perilaku Pegawai
            [
                'indikator_id' => 12,
                'kode' => 'a',
                'pertanyaan' => 'Aturan disiplin/kode etik/kode perilaku telah dilaksanakan/diimplementasikan',
                'penjelasan' => 'a. Jika unit kerja telah mengimplementasikan seluruh aturan disiplin/kode etik/kode perilaku yang ditetapkan organisasi dan juga membuat inovasi terkait aturan disiplin/kode etik/kode perilaku yang sesuai dengan karakteristik unit kerja b. Jika unit kerja telah mengimplementasikan seluruh aturan disiplin/kode etik/kode perilaku yang ditetapkan organisasi c. Jika unit kerja telah mengimplementasikan sebagian aturan disiplin/kode etik/kode perilaku yang ditetapkan organisasi d. Jika unit kerja belum mengimplementasikan aturan disiplin/kode etik/kode perilaku yang ditetapkan organisasi',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 13: Sistem Informasi Kepegawaian
            [
                'indikator_id' => 13,
                'kode' => 'a',
                'pertanyaan' => 'Data informasi kepegawaian unit kerja telah dimutakhirkan secara berkala',
                'penjelasan' => 'a. Jika data informasi kepegawaian unit kerja dapat diakses oleh pegawai dan dimutakhirkan setiap ada perubahan data pegawai b. Jika data informasi kepegawaian unit kerja dapat diakses oleh pegawai dan dimutakhirkan namun secara berkala c. Jika data informasi kepegawaian unit kerja belum dimutakhirkan',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 14: Keterlibatan Pimpinan
            [
                'indikator_id' => 14,
                'kode' => 'a',
                'pertanyaan' => 'Unit kerja telah melibatkan pimpinan secara langsung pada saat penyusunan perencanaan',
                'penjelasan' => 'a. Jika pimpinan selalu terlibat dalam seluruh tahapan penyusunan perencanaan b. Jika pimpinan ikut terlibat dalam sebagian tahapan penyusunan perencanaan c. Jika tidak ada keterlibatan pimpinan dalam penyusunan perencanaan (hanya menandatangani)',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 14,
                'kode' => 'b',
                'pertanyaan' => 'Unit kerja telah melibatkan secara langsung pimpinan saat penyusunan penetapan kinerja',
                'penjelasan' => 'a. Jika pimpinan selalu terlibat dalam seluruh tahapan penyusunan perjanjian kinerja b. Jika pimpinan terlibat dalam sebagian tahapan penyusunan perjanjian kinerja c. Jika tidak ada keterlibatan pimpinan dalam penyusunan perjanjian kinerja',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 14,
                'kode' => 'c',
                'pertanyaan' => 'Pimpinan memantau pencapaian kinerja secara berkala',
                'penjelasan' => 'a. Jika pimpinan selalu terlibat dalam seluruh pemantauan pencapaian kinerja dan menindaklanjuti hasil pemantauan b. Jika pimpinan unit kerja terlibat dalam seluruh pemantauan pencapaian kinerja tetapi tidak ada tindak lanjut hasil pemantauan c. Jika pimpinan unit kerja terlibat dalam sebagian pemantauan pencapaian kinerja d. Jika tidak ada keterlibatan pimpinan dalam pemantauan pencapaian kinerja',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 15: Pengelolaan Akuntabilitas Kinerja
            [
                'indikator_id' => 15,
                'kode' => 'a',
                'pertanyaan' => 'Dokumen perencanaan kinerja sudah ada',
                'penjelasan' => 'ya, jika unit kerja memiliki dokumen perencanaan kinerja lengkap',
                'tipe_jawaban' => 'ya_tidak',
                'pilihan_jawaban' => json_encode(['Ya', 'Tidak']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 15,
                'kode' => 'b',
                'pertanyaan' => 'Perencanaan kinerja telah berorientasi hasil',
                'penjelasan' => 'ya, jika perencanaan kinerja telah berorientasi hasil',
                'tipe_jawaban' => 'ya_tidak',
                'pilihan_jawaban' => json_encode(['Ya', 'Tidak']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 15,
                'kode' => 'c',
                'pertanyaan' => 'Terdapat penetapan Indikator Kinerja Utama (IKU)',
                'penjelasan' => 'ya, jika unit kerja memiliki IKU',
                'tipe_jawaban' => 'ya_tidak',
                'pilihan_jawaban' => json_encode(['Ya', 'Tidak']),
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 15,
                'kode' => 'd',
                'pertanyaan' => 'Indikator kinerja telah telah memenuhi kriteria SMART',
                'penjelasan' => 'a. Jika seluruh indikator kinerja telah SMART b. Jika sebagian besar indikator kinerja telah SMART c. Jika sebagian kecil indikator kinerja telah SMART d. Jika belum ada indikator kinerja yang SMART',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 15,
                'kode' => 'e',
                'pertanyaan' => 'Laporan kinerja telah disusun tepat waktu',
                'penjelasan' => 'Ya, jika unit kerja telah menyusun laporan kinerja tepat waktu',
                'tipe_jawaban' => 'ya_tidak',
                'pilihan_jawaban' => json_encode(['Ya', 'Tidak']),
                'urutan' => 5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 15,
                'kode' => 'f',
                'pertanyaan' => 'Laporan kinerja telah memberikan informasi tentang kinerja',
                'penjelasan' => 'a. Jika seluruh pelaporan kinerja telah memberikan informasi tentang kinerja b. Jika sebagian pelaporan kinerja belum memberikan informasi tentang kinerja c. Jika seluruh pelaporan kinerja belum memberikan informasi tentang kinerja',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 6,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 15,
                'kode' => 'g',
                'pertanyaan' => 'Terdapat sistem informasi/mekanisme informasi kinerja',
                'penjelasan' => 'ya, jika terdapat sistem informasi/mekanisme informasi kinerja',
                'tipe_jawaban' => 'ya_tidak',
                'pilihan_jawaban' => json_encode(['Ya', 'Tidak']),
                'urutan' => 7,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 15,
                'kode' => 'h',
                'pertanyaan' => 'Unit kerja telah berupaya meningkatkan kapasitas SDM yang menangangi akuntabilitas kinerja',
                'penjelasan' => 'a. Jika seluruh SDM pengelola akuntabilitas kinerja kompeten b. Jika sebagian SDM pengelola akuntabilitas kinerja kompeten c. Jika seluruh SDM pengelola akuntabilitas kinerja belum ada yang kompeten',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 8,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Indikator 16: Pengendalian Gratifikasi
            [
                'indikator_id' => 16,
                'kode' => 'a',
                'pertanyaan' => 'Telah dilakukan public campaign tentang pengendalian gratifikasi',
                'penjelasan' => 'a. Jika public campaign telah dilakukan secara berkala b. Jika public campaign dilakukan tidak secara berkala c. Jika belum dilakukan public campaign',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 16,
                'kode' => 'b',
                'pertanyaan' => 'Pengendalian gratifikasi telah diimplementasikan',
                'penjelasan' => 'a. Jika Unit Pengendalian Gratifikasi, pengendalian gratifikasi telahmenjadi bagian dari prosedur b. Jika Unit Pengendalian Gratifikasi, upaya pengendalian gratifikasi telah mulai dilakukan c. Jika telah membentuk Unit Pengendalian Gratifikasi tetapi belum terdapat prosedur pengendalian d. Jika belum memiliki Unit Pengendalian Gratifikasi',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 17: Penerapan Sistem Pengendalian Intern Pemerintah (SPIP)
            [
                'indikator_id' => 17,
                'kode' => 'a',
                'pertanyaan' => 'Telah dibangun lingkungan pengendalian',
                'penjelasan' => 'a. Jika unit kerja membangun seluruh lingkungan pengendalian sesuai dengan yang ditetapkan organisasi dan juga membuat inovasi terkait lingkungan pengendalian yang sesuai dengan karakteristik unit kerja b. Jika unit kerja membangun seluruh lingkungan pengendalian sesuai dengan yang ditetapkan organisasi c. Jika unit kerja membangun sebagian besar lingkungan pengendalian sesuai dengan yang ditetapkan organisasi d. Jika unit kerja membangun sebagian kecil lingkungan pengendalian sesuai dengan yang ditetapkan organisasi e. Jika unit kerja belum membangun lingkungan pengendalian',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D', 'E']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 17,
                'kode' => 'b',
                'pertanyaan' => 'Telah dilakukan penilaian risiko atas pelaksanaan kebijakan',
                'penjelasan' => 'a. Jika unit kerja melakukan penilaian risiko atas seluruh pelaksanaan kebijakan sesuai dengan yang ditetapkan organisasi dan juga membuat inovasi terkait lingkungan pengendalian yang sesuai dengan karakteristik unit kerja; b. Jika unit kerja melakukan penilaian risiko atas seluruh pelaksanaan kebijakan sesuai dengan yang ditetapkan organisasi c. Jika melakukan penilaian risiko atas sebagian besar pelaksanaan kebijakan sesuai dengan yang ditetapkan organisasi d. Jika melakukan penilaian risiko atas sebagian kecil pelaksanaan kebijakan sesuai dengan yang ditetapkan organisasi e. Jika unit kerja belum melakukan penilaian resiko',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D', 'E']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 17,
                'kode' => 'c',
                'pertanyaan' => 'Telah dilakukan kegiatan pengendalian untuk meminimalisir risiko yang telah diidentifikasi',
                'penjelasan' => 'a. Jika unit kerja melakukan kegiatan pengendalian untuk meminimalisir resiko sesuai dengan yang ditetapkan organisasi dan juga membuat inovasi terkait kegiatan pengendalian untuk meminimalisir resiko yang sesuai dengan karakteristik unit kerja b. Jika unit kerja melakukan kegiatan pengendalian untuk meminimalisir resiko sesuai dengan yang ditetapkan organisasi c. Jika unit kerja belum melakukan kegiatan pengendalian untuk meminimalisir resiko',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 17,
                'kode' => 'd',
                'pertanyaan' => 'SPI telah diinformasikan dan dikomunikasikan kepada seluruh pihak terkait',
                'penjelasan' => 'a. Jika SPI telah diinformasikan dan dikomunikasikan kepada seluruh pihak terkait b. Jika SPI telah diinformasikan dan dikomunikasikan kepada sebagian pihak terkait c. Jika SPI belum diinformasikan dan dikomunikasikan kepada pihak terkait',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 18: Pengaduan Masyarakat
            [
                'indikator_id' => 18,
                'kode' => 'a',
                'pertanyaan' => 'Kebijakan Pengaduan masyarakat telah diimplementasikan',
                'penjelasan' => 'a. Jika unit kerja mengimplementasikan seluruh kebijakan pengaduan masyarakat sesuai dengan yang ditetapkan organisasi dan juga membuat inovasi terkait pengaduan masyarakat yang sesuai dengan karakteristik unit kerja b. Jika unit kerja telah mengimplementasikan seluruh kebijakan pengaduan masyarakat sesuai dengan yang ditetapkan organisasi c. Jika unit kerja belum mengimplementasikan kebijakan pengaduan masyarakat',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 18,
                'kode' => 'b',
                'pertanyaan' => 'pengaduan masyarakat dtindaklanjuti',
                'penjelasan' => 'ya,pengaduan masyaakat ditindaklanjuti',
                'tipe_jawaban' => 'ya_tidak',
                'pilihan_jawaban' => json_encode(['Ya', 'Tidak']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 18,
                'kode' => 'c',
                'pertanyaan' => 'Telah dilakukan monitoring dan evaluasi atas penanganan pengaduan masyarakat',
                'penjelasan' => 'a. Jika penanganan pengaduan masyarakat dimonitoring dan evaluasi secara berkala b. Jika penanganan pengaduan masyarakat dimonitoring dan evaluasi tetapi tidak secara berkala c. Jika penanganan pengaduan masyarakat belum di monitoring dan evaluasi',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 18,
                'kode' => 'd',
                'pertanyaan' => 'Hasil evaluasi atas penanganan pengaduan masyarakat telah ditindaklanjuti',
                'penjelasan' => 'a. Jika seluruh hasil evaluasi atas penanganan pengaduan telah ditindaklanjuti oleh unit kerja b. Jika sebagian hasil evaluasi atas penanganan pengaduan telah ditindaklanjuti oleh unit kerja c. Jika hasil evaluasi atas penanganan pengaduan belum ditindaklanjuti',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 19: Whistle-Blowing System
            [
                'indikator_id' => 19,
                'kode' => 'a',
                'pertanyaan' => 'Whistle Blowing System telah diterapkan',
                'penjelasan' => 'a. Jika unit kerja menerapkan seluruh kebijakan Whistle Blowing System sesuai dengan yang ditetapkan organisasi dan juga membuat inovasi terkait pelaksanaan Whistle Blowing System yang sesuai dengan karakteristik unit kerja b. Jika unit kerja menerapkan kebijakan Whistle Blowing System sesuai dengan yang ditetapkan organisasi c. Jika unit kerja belum menerapkan kebijakan Whistle Blowing System',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 19,
                'kode' => 'b',
                'pertanyaan' => 'Telah dilakukan evaluasi atas penerapan Whistle Blowing System',
                'penjelasan' => 'a. Jika penerapan Whistle Blowing System dimonitoring dan evaluasi secara berkala b. Jika penerapan Whistle Blowing System dimonitoring dan evaluasi tidak secara berkala c. Jika penerapan Whistle Blowing System belum di monitoring dan evaluasi',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 19,
                'kode' => 'c',
                'pertanyaan' => 'Hasil evaluasi atas penerapan Whistle Blowing System telah ditindaklanjuti',
                'penjelasan' => 'a. Jika seluruh hasil evaluasi atas penerapan Whistle Blowing System telah ditindaklanjuti oleh unit kerja b. Jika sebagian hasil evaluasi atas penerapan Whistle Blowing System telah ditindaklanjuti oleh unit kerja c. Jika hasil evaluasi atas penerapan Whistle Blowing System belum ditindaklanjuti',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 20: Penanganan Benturan Kepentingan
            [
                'indikator_id' => 20,
                'kode' => 'a',
                'pertanyaan' => 'Telah terdapat identifikasi/pemetaan benturan kepentingan dalam tugas fungsi utama',
                'penjelasan' => 'a. Jika terdapat  identifikasi/pemetaan benturan kepentingan pada seluruh tugas fungsi utama b. Jika terdapat  identifikasi/pemetaan benturan kepentingan tetapi pada sebagian besar tugas fungsi utama c. Jika terdapat  identifikasi/pemetaan benturan kepentingan tetapi pada sebagian kecil tugas fungsi utama d. Jika belum terdapat  identifikasi/pemetaan benturan kepentingan dalam tugas fungsi utama',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 20,
                'kode' => 'b',
                'pertanyaan' => 'Penanganan Benturan Kepentingan telah disosialisasikan/internalisasi',
                'penjelasan' => 'a. Jika penanganan Benturan Kepentingan disosialiasikan/diinternalisasikan ke seluruh layanan b. Jika penanganan Benturan Kepentingan disosialiasikan/diinternalisasikan ke sebagian besar layanan c.  Jika penanganan Benturan Kepentingan disosialiasikan/diinternalisasikan ke sebagian kecil layanan d.  Jika penanganan Benturan Kepentingan belum disosialiasikan/diinternalisasikan ke seluruh layanan',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 20,
                'kode' => 'c',
                'pertanyaan' => 'Penanganan Benturan Kepentingan telah diimplementasikan',
                'penjelasan' => 'a. Jika penanganan Benturan Kepentingan diimplementasikan ke seluruh layanan b. Jika penanganan Benturan Kepentingan diimplementasikan ke sebagian besar layanan c. Jika penanganan Benturan Kepentingan diimplementasikan ke sebagian kecil layanan d. Jika penanganan Benturan Kepentingan belum diimplementasikan ke seluruh layanan',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 20,
                'kode' => 'd',
                'pertanyaan' => 'Telah dilakukan evaluasi atas Penanganan Benturan Kepentingan',
                'penjelasan' => 'a. Jika penanganan Benturan Kepentingan dievaluasi secara berkala oleh unit kerja b. Jika penanganan Benturan Kepentingan dievaluasi tetapi tidak secara berkala oleh unit kerja c. Jika penanganan Benturan Kepentingan belum dievaluasi oleh unit kerja',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 20,
                'kode' => 'e',
                'pertanyaan' => 'Hasil evaluasi atas Penanganan Benturan Kepentingan telah ditindaklanjuti',
                'penjelasan' => 'a. Jika seluruh hasil evaluasi atas Penanganan Benturan Kepentingan telah ditindaklanjuti oleh unit kerja b. Jika sebagian hasil evaluasi atas Penanganan Benturan Kepentingan telah ditindaklanjuti oleh unit kerja c. Jika belum ada hasil evaluasi atas Penanganan Benturan Kepentingan yang ditindaklanjuti unit kerja',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 21: Standar Pelayanan
            [
                'indikator_id' => 21,
                'kode' => 'a',
                'pertanyaan' => 'Terdapat kebijakan standar pelayanan',
                'penjelasan' => 'a. Terdapat penetapan Standar Pelayanan terhadap seluruh jenis pelayanan, dan sesuai asas serta komponen standar pelayanan publik yang berlaku b. Terdapat penetapan Standar Pelayanan terhadap sebagian jenis pelayanan, dan sesuai asas serta komponen standar pelayanan publik yang berlaku c. Terdapat penetapan Standar Pelayanan terhadap seluruh jenis pelayanan, namun tidak sesuai asas serta komponen standar pelayanan publik yang berlaku d. Terdapat penetapan Standar Pelayanan terhadap sebagian jenis pelayanan, namun tidak sesuai asas serta komponen standar pelayanan publik yang berlaku e. Standar Pelayanan belum ditetapkan',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D', 'E']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 21,
                'kode' => 'b',
                'pertanyaan' => 'Standar pelayanan telah dimaklumatkan',
                'penjelasan' => 'a. Standar pelayanan telah dimaklumatkan pada seluruh jenis pelayanan dan dipublikasikan di website dan media lainnya b. Standar pelayanan telah dimaklumatkan pada sebagian besar jenis pelayanan dan dipublikasikan minimal di website c. Standar pelayanan telah dimaklumatkan pada sebagian kecil  jenis pelayanan dan belum dipublikasikan d. Standar pelayanan belum dimaklumatkan pada seluruh jenis pelayanan dan belum dipublikasikan',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 21,
                'kode' => 'c',
                'pertanyaan' => 'Dilakukan reviu dan perbaikan atas standar pelayanan',
                'penjelasan' => 'a. Dilakukan reviu dan perbaikan atas standar pelayanan dan dilakukan dengan melibatkan stakeholders (antara lain : tokoh masyarakat,  akademisi, dunia usaha, dan lembaga swadaya masyarakat), serta memanfaatkan masukan hasil SKM dan pengaduan masyarakat b. Dilakukan reviu dan perbaikan atas standar pelayanan dan dilakukan dengan memanfaatkan masukan hasil SKM dan pengaduan masyarakat, namun tanpa melibatkan stakeholders c. Dilakukan reviu dan perbaikan atas standar pelayanan, namun  dilakukan tanpa memanfaatkan masukan hasil SKM dan pengaduan masyarakat, serta tanpa melibatkan stakeholders d. Belum dilakukan reviu dan perbaikan atas standar pelayanan',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 21,
                'kode' => 'd',
                'pertanyaan' => 'telah melakukan publikasi atas standar pelayanan dan maklumat pelayanan',
                'penjelasan' => 'ya,telah melakukan publikasi atas tandar pelayanan dan maklumat pelayanan',
                'tipe_jawaban' => 'ya_tidak',
                'pilihan_jawaban' => json_encode(['Ya', 'Tidak']),
                'urutan' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 22: Budaya Pelayanan Prima
            [
                'indikator_id' => 22,
                'kode' => 'a',
                'pertanyaan' => 'Telah dilakukan berbagai upaya peningkatan kemampuan dan/atau kompetensi tentang penerapan budaya pelayanan prima',
                'penjelasan' => 'a. Telah dilakukan pelatihan/sosialisasi pelayanan prima secara berkelanjutan dan terjadwal, sehingga seluruh petugas/pelaksana layanan memiliki kompetensi sesuai kebutuhan jenis layanan serta telah dan terdapat monev yang melihat kemampuan/kecakapan petugas/pelaksana layanan b. Telah dilakukan pelatihan/sosialisasi pelayanan prima, dan  seluruh petugas/pelaksana layanan memiliki kompetensi sesuai kebutuhan jenis layanan c. Telah dilakukan pelatihan/sosialisasi pelayanan prima, akan tetapi baru sebagian besar petugas/pelaksana layanan memiliki kompetensi sesuai kebutuhan jenis layanan d. Telah dilakukan pelatihan/sosialisasi pelayanan prima namun secara terbatas, sehingga hanya sebagian kecil petugas/pelaksana layanan yang memiliki kompetensi sesuai kebutuhan jenis layanan e. Belum dilakukan pelatihan/sosialisasi pelayanan prima, dan seluruh petugas/pelaksana layanan belum memiliki kompetensi sesuai kebutuhan jenis layanan',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D', 'E']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 22,
                'kode' => 'b',
                'pertanyaan' => 'Informasi tentang pelayanan mudah diakses melalui berbagai media',
                'penjelasan' => 'a. Seluruh Informasi tentang pelayanan dapat diakses secara online (website/media sosial) dan terhubung dengan sistem informasi pelayanan publik nasional b. Seluruh Informasi tentang pelayanan dapat diakses secara online (website/media sosial), namun belum terhubung dengan sistem informasi pelayanan publik nasional c. Seluruh Informasi tentang pelayanan belum online, hanya dapat diakses di tempat layanan (intranet dan non elektronik) d. Informasi tentang pelayanan sulit diakses',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 22,
                'kode' => 'c',
                'pertanyaan' => 'Telah terdapat sistem pemberian penghargaan dan sanksi bagi petugas pemberi pelayanan',
                'penjelasan' => 'a. Telah terdapat kebijakan pemberian penghargaan dan sanksi yang minimal memenuhi unsur penilaian: disiplin, kinerja, dan hasil penilaian pengguna layanan, dan telah diterapkan secara rutin/berkelanjutan b. Telah terdapat kebijakan pemberian penghargaan dan sanksi yang minimal memenuhi unsur penilaian: disiplin, kinerja, dan hasil penilaian pengguna layanan, namun belum diterapkan secara rutin/berkelanjutan c. Telah terdapat kebijakan pemberian penghargaan dan sanksi, namun belum memenuhi unsur penilaian minimal : disiplin, kinerja, dan hasil penilaian pengguna layanan d. Belum terdapat kebijakan pemberian penghargaan dan sanksi',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 22,
                'kode' => 'd',
                'pertanyaan' => 'Telah terdapat sistem pemberian kompensasi kepada penerima layanan bila layanan tidak sesuai standar',
                'penjelasan' => 'a. Telah terdapat sistem pemberian kompensasi bila layanan tidak sesuai standar bagi penerima layanan di seluruh jenis layanan b. Telah terdapat sistem pemberian kompensasi bila layanan tidak sesuai standar bagi penerima layanan di sebagian besar jenis layanan c. Telah terdapat sistem pemberian kompensasi bila layanan tidak sesuai standar bagi penerima layanan di sebagian kecil jenis layanan d. Belum terdapat sistem pemberian kompensasi bila layanan tidak sesuai standar',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 22,
                'kode' => 'e',
                'pertanyaan' => 'Terdapat sarana layanan terpadu/terintegrasi',
                'penjelasan' => 'a. Jika seluruh pelayanan sudah dilakukan secara terpadu/terintegrasi b. Jika sebagian besar pelayanan sudah dilakukan secara terpadu/terintegrasi c. Jika sebagian kecil pelayanan sudah dilakukan secara terpadu/terintegrasi d. Jika tidak ada pelayanan yang dilakukan secara terpadu/terintegrasi',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 22,
                'kode' => 'f',
                'pertanyaan' => 'Terdapat inovasi pelayanan',
                'penjelasan' => 'a. Jika unit kerja telah memiliki inovasi pelayanan yang  berbeda dengan unit kerja lain dan mendekatkan pelayanan dengan masyarakat serta telah direplikasi b. Jika unit kerja telah memiliki inovasi pelayanan yang  berbeda dengan unit kerja lain dan mendekatkan pelayanan dengan masyarakat c. Jika unit kerja memiliki inovasi yang merupakan replikasi dan pengembangan dari inovasi yang sudah ada d. Jika unit kerja telah memiliki inovasi akan tetapi merupakan pelaksanaan inovasi dari instansi pemerintah e. Jika  unit kerja belum memiliki inovasi pelayanan',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D', 'E']),
                'urutan' => 6,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 23: Pengelolaan Pengaduan
            [
                'indikator_id' => 23,
                'kode' => 'a',
                'pertanyaan' => 'Terdapat media pengaduan dan konsultasi pelayanan yang terintegrasi dengan SP4N-Lapor!',
                'penjelasan' => 'a. Terdapat media konsultasi dan pengaduan secara offline dan online, tersedia petugas khusus yang menangani, dan terintegrasi dengan SP4N-LAPOR! b. Terdapat media konsultasi dan pengaduan secara offline dan online, tersedia petugas khusus yang menangani namun belum terintegrasi dengan SP4N-LAPOR! c. Terdapat media konsultasi dan pengaduan secara offline dan online, namun belum tersedia petugas khusus yang menangani d. Hanya terdapat media konsultasi dan pengaduan secara offline e. Tidak terdapat media konsultasi dan pengaduan',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D', 'E']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 23,
                'kode' => 'b',
                'pertanyaan' => 'Terdapat unit yang mengelola pengaduan dan konsultasi pelayanan',
                'penjelasan' => 'a. Terdapat unit pengelola khusus untuk konsultasi dan pengaduan, serta surat penugasan pengelola SP4N-LAPOR! di level unit kerja b. Terdapat SK pengelola SP4N-LAPOR! di level instansi dan/atau surat penugasan pengelola SP4N-LAPOR! di level unit kerja, namun unit pengelola khusus untuk konsultasi dan pengaduan belum ada c. Belum terdapat unit pengelola khusus untuk konsultasi dan pengaduan, serta belum terdapat SK pengelola SP4N-LAPOR! di level instansi dan/atau surat penugasan pengelola SP4N-LAPOR! di level unit kerja',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 23,
                'kode' => 'c',
                'pertanyaan' => 'Telah dilakukan evaluasi atas penanganan keluhan/masukan dan konsultasi',
                'penjelasan' => 'a. Evaluasi atas penanganan keluhan/masukan dan konsultasi dilakukan secara berkala b. Evaluasi  atas penanganan keluhan/masukan dan konsultasi dilakukan  tidak berkala c. Belum dilakukan evaluasi penanganan keluhan/masukan dan konsultasi',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 24: Penilaian Kepuasan terhadap Pelayanan
            [
                'indikator_id' => 24,
                'kode' => 'a',
                'pertanyaan' => 'Telah dilakukan survey kepuasan masyarakat terhadap pelayanan',
                'penjelasan' => 'a. Survei kepuasan masyarakat terhadap pelayanan dilakukan minimal 4 kali dalam setahun b. Survei kepuasan masyarakat terhadap pelayanan dilakukan minimal 3 kali dalam setahun c. Survei kepuasan masyarakat terhadap pelayanan dilakukan minimal 2 kali dalam setahun d. Survei kepuasan masyarakat terhadap pelayanan dilakukan minimal 1 kali dalam setahun e. Belum dilakukan survei kepuasan masyarakat terhadap pelayanan',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D', 'E']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 24,
                'kode' => 'b',
                'pertanyaan' => 'Hasil survei kepuasan masyarakat dapat diakses secara terbuka',
                'penjelasan' => 'a. Hasil survei kepuasan masyarakat dapat diakses secara  online (website, media sosial, dll) dan offline b. Hasil survei kepuasan masyarakat hanya dapat diakses secara offline di tempat layanan c. Hasil survei kepuasan masyarakat tidak dipublikasi',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 24,
                'kode' => 'c',
                'pertanyaan' => 'Dilakukan tindak lanjut atas hasil survei kepuasan masyarakat',
                'penjelasan' => 'a. Jika dilakukan tindak lanjut atas seluruh hasil survei kepuasan masyarakat b. Jika dilakukan tindak lanjut atas sebagian besar hasil survei kepuasan masyarakat c. Jika dilakukan tindak lanjut atas sebagian kecil hasil survei kepuasan masyarakat d. Jika belum dilakukan tindak lanjut atas hasil survei kepuasan masyarakat',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 25: Pemanfaatan Teknologi Informasi
            [
                'indikator_id' => 25,
                'kode' => 'a',
                'pertanyaan' => 'Telah menerapkan teknologi informasi dalam memberikan pelayanan',
                'penjelasan' => 'a. Terdapat pelayanan yang menggunakan teknologi informasi pada seluruh proses pemberian layanan b. Terdapat pelayanan yang menggunakan teknologi informasi pada sebagian besar proses pemberian layanan c. Terdapat pelayanan yang menggunakan teknologi informasi pada sebagian kecil proses pemberian layanan d. Terdapat pelayanan yang belum menggunakan teknologi informasi pada proses pemberian pelayanan',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 25,
                'kode' => 'b',
                'pertanyaan' => 'Telah dilakukan perbaikan secara terus menerus',
                'penjelasan' => 'a. Perbaikan dilakukan secara terus-menerus b. Perbaikan dilakukan tidak secara terus menerus c. Belum dilakukan perbaikan',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 25,
                'kode' => 'c',
                'pertanyaan' => 'Telah membangun database pelayanan yang terintegrasi',
                'penjelasan' => 'Ya,jika tela membangun database pelayanan yang terintegrasi',
                'tipe_jawaban' => 'ya_tidak',
                'pilihan_jawaban' => json_encode(['Ya', 'Tidak']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 26: Komitmen dalam perubahan
            [
                'indikator_id' => 26,
                'kode' => 'a',
                'pertanyaan' => 'Agen perubahan telah membuat perubahan yang konkret di Instansi (dalam 1 tahun)',
                'penjelasan' => 'Misalkan dengan kebijakan 1 Agen 1 Perubahan Persentase diperoleh dari Jumlah Perubahan yang dibuat dibagi dengan Jumlah Agen Perubahan',
                'tipe_jawaban' => 'angka',
                'pilihan_jawaban' => json_encode([]),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 26,
                'kode' => 'b',
                'pertanyaan' => 'Perubahan yang dibuat Agen Perubahan telah terintegrasi dalam sistem manajemen',
                'penjelasan' => 'Persentase diperoleh dari Jumlah Perubahan yang telah diintegrasikan dalam sistem manajemen dibagi dengan Jumlah Perubahan yang dibuat',
                'tipe_jawaban' => 'angka',
                'pilihan_jawaban' => json_encode([]),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 27: Komitmen Pimpinan
            [
                'indikator_id' => 27,
                'kode' => 'a',
                'pertanyaan' => 'Pimpinan memiliki komitmen terhadap pelaksanaan reformasi birokrasi, dengan adanya target capaian reformasi yang jelas di dokumen perencanaan',
                'penjelasan' => 'a. Target capaian zona integritas sudah ada di dokumen perencanaan unit kerja dan sebagian besar (diatas 80%) sudah tercapai b. Target capaian zona integritas sudah ada di dokumen perencanaan unit kerja dan sebagian (diatas 50%) sudah tercapai c. Target capaian zona integritas sudah ada di dokumen perencanaan unit kerja dan sebagian kecil (dibawah 50%) sudah tercapai d. Target capaian zona integritassudah ada di dokumen perencanaan unit kerja, namun belum ada yang tercapai (masih dalam tahap pembangunan) e. Tidak ada target capaian zona integritasdi dokumen perencanaan unit kerja',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D', 'E']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 28: Membangun Budaya Kerja
            [
                'indikator_id' => 28,
                'kode' => 'a',
                'pertanyaan' => 'Instansi membangun budaya kerja positif dan menerapkan nilai-nilai organisasi dalam pelaksanaan tugas sehari-hari',
                'penjelasan' => 'a. Budaya kerja dan nilai-nilai organisasi telah dinternalisasi ke seluruh anggota organisasi, dan penerapannya dituangkan dalam standar operasional pelaksanaan kegiatan/tugas b. Budaya kerja dan nilai-nilai organisasi telah dinternalisasi ke seluruh anggota organisasi, namun belum dituangkan dalam standar operasional pelaksanaan kegiatan/tugas c. Budaya kerja dan nilai-nilai organisasi telah disusun, namun belum dinternalisasi ke seluruh anggota organisasi d. Belum menyusun budaya kerja dan nilai-nilai organisasi',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 29: Peta Proses Bisnis Mempengaruhi Penyederhanaan Jabatan
            [
                'indikator_id' => 29,
                'kode' => 'a',
                'pertanyaan' => 'Telah disusun peta proses bisnis dengan adanya penyederhanaan jabatan',
                'penjelasan' => 'a. Peta proses bisnis telah disusun dan mempengaruhi penyederhanaan seluruh jabatan b. Peta proses bisnis telah disusun dan mempengaruhi penyederhanaan sebagian besar (lebih dari 50%) jabatan c. Peta proses bisnis telah disusun dan mempengaruhi penyederhanaan sebagian kecil (kurang dari 50%)  jabatan d. Peta proses bisnis telah disusun dan belum mempengaruhi penyederhanaan jabatan',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 30: Sistem Pemerintahan Berbasis Elektronik (SPBE) yang Terintegrasi
            [
                'indikator_id' => 30,
                'kode' => 'a',
                'pertanyaan' => 'Implementasi SPBE telah terintegrasi dan mampu mendorong pelaksanaan pelayanan publik yang lebih cepat dan efisien',
                'penjelasan' => 'a. Implementasi SPBE telah terintegrasi dan mampu mendorong pelaksanaan pelayanan publik yang lebih cepat dan efisien b. Implementasi SPBE telah mampu mendorong pelaksanaan pelayanan publik yang lebih cepat dan efisien, namun belum terintegrasi (parsial) c. Implementasi SPBE belum mendorong pelaksanaan pelayanan publik yang lebih cepat dan efisien',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 30,
                'kode' => 'b',
                'pertanyaan' => 'Implementasi SPBE telah terintegrasi dan mampu mendorong pelaksanaan pelayanan internal organisasi yang lebih cepat dan efisien',
                'penjelasan' => 'a. Implementasi SPBE telah terintegrasi dan mampu mendorong pelaksanaan pelayanan internal unit kerja yang lebih cepat dan efisien b. Implementasi SPBE telah mampu mendorong pelaksanaan pelayanan internal unit kerja yang lebih cepat dan efisien, namun belum terintegrasi (parsial) c. Implementasi SPBE belum mendorong pelaksanaan pelayanan internal unit kerja yang lebih cepat dan efisien',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 31: Transformasi Digital Memberikan Nilai Manfaat
            [
                'indikator_id' => 31,
                'kode' => 'a',
                'pertanyaan' => 'Transformasi digital pada bidang proses bisnis utama telah mampu memberikan nilai manfaat bagi unit kerja secara optimal',
                'penjelasan' => 'a. Kriteria huruf b telah terpenuhi dan penerapan atau penggunaan dari manfaat/dampak dari transformasi digital pada bidang proses bisnis utama bagi unit kerja telah dilakukan validasi dan evaluasi serta ditindaklanjuti secara berkelanjutan b. Kriteria huruf c telah terpenuhi dan manfaat/dampak dari transformasi digital pada bidang proses bisnis utama telah diterapkan/digunakan oleh unit kerja sesuai dengan sasaran dan target manfaat/dampak c. Kriteria huruf d telah terpenuhi dan manfaat/dampak dari transformasi digital pada bidang proses bisnis utama telah mampu direalisasikan pada unit kerja sesuai dengan sasaran dan target manfaat/dampak d. Kriteria huruf e telah terpenuhi dan kapabilitas prakiraan dan pelacakan terhadap sasaran dan target manfaat/dampak dari transformasi digital pada bidang proses bisnis utama e. Sasaran dan target manfaat/dampak dari transformasi digital pada bidang proses bisnis utama telah direncanakan, didefinisikan, dan ditetapkan',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D', 'E']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 31,
                'kode' => 'b',
                'pertanyaan' => 'Transformasi digital pada bidang administrasi pemerintahan telah mampu memberikan nilai manfaat bagi unit kerja secara optimal',
                'penjelasan' => 'a. Kriteria huruf b telah terpenuhi dan penerapan atau penggunaan dari manfaat/dampak dari transformasi digital pada bidang administrasi pemerintahan bagi unit kerja telah dilakukan validasi dan evaluasi serta ditindaklanjuti secara berkelanjutan b. Kriteria huruf c telah terpenuhi dan manfaat/dampak dari transformasi digital pada bidang administrasi pemerintahan telah diterapkan/digunakan oleh unit kerja sesuai dengan sasaran dan target manfaat/dampak c. Kriteria huruf d telah terpenuhi dan manfaat/dampak dari transformasi digital pada bidang administrasi pemerintahan telah mampu direalisasikan pada unit kerja sesuai dengan sasaran dan target manfaat/dampak d. Kriteria huruf e telah terpenuhi dan kapabilitas prakiraan dan pelacakan terhadap sasaran dan target manfaat/dampak dari transformasi digital pada bidang administrasi pemerintahan e. Sasaran dan target manfaat/dampak dari transformasi digital pada bidang administrasi pemerintahan telah direncanakan, didefinisikan, dan ditetapkan',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D', 'E']),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 31,
                'kode' => 'c',
                'pertanyaan' => 'Transformasi digital pada bidang pelayanan publik telah mampu memberikan nilai manfaat bagi unit kerja secara optimal',
                'penjelasan' => 'a. Kriteria huruf b telah terpenuhi dan penerapan atau penggunaan dari manfaat/dampak dari transformasi digital pada bidang pelayanan publik bagi unit kerja telah dilakukan validasi dan evaluasi serta ditindaklanjuti secara berkelanjutan b. Kriteria huruf c telah terpenuhi dan manfaat/dampak dari transformasi digital pada bidang pelayanan publik telah diterapkan/digunakan oleh unit kerja sesuai dengan sasaran dan target manfaat/dampak c. Kriteria huruf d telah terpenuhi dan manfaat/dampak dari transformasi digital pada bidang pelayanan publik telah mampu direalisasikan pada unit kerja sesuai dengan sasaran dan target manfaat/dampak d. Kriteria huruf e telah terpenuhi dan kapabilitas prakiraan dan pelacakan terhadap sasaran dan target manfaat/dampak dari transformasi digital pada bidang pelayanan publik e. Sasaran dan target manfaat/dampak dari transformasi digital pada bidang pelayanan publik telah direncanakan, didefinisikan, dan ditetapkan',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D', 'E']),
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 32: Kinerja Individu
            [
                'indikator_id' => 32,
                'kode' => 'a',
                'pertanyaan' => 'Ukuran kinerja individu telah berorientasi hasil (outcome) sesuai pada levelnya',
                'penjelasan' => 'a. Seluruh ukuran kinerja individu telah berorientasi hasil (outcome) sesuai pada levelnya b. Sebagian ukuran kinerja individu telah berorientasi hasil (outcome) sesuai pada levelnya c. Tidak ada ukuran kinerja individu yang berorientasi hasil (outcome)',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 33: Assessment Pegawai
            [
                'indikator_id' => 33,
                'kode' => 'a',
                'pertanyaan' => 'Hasil assement telah dijadikan pertimbangan untuk mutasi dan pengembangan karir pegawai',
                'penjelasan' => 'a. Seluruh hasil assessment dijadikan dasar mutasi internal dan pengembangan kompetensi pegawai b. Hasil assessment belum seluruhnya dijadikan mutasi internal dan pengembangan kompetensi pegawai c. Hasil assessment belum dijadikan dasar mutasi internal dan pengembangan kompetensi pegawai',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 34: Pelanggaran Disiplin Pegawai
            [
                'indikator_id' => 34,
                'kode' => 'a',
                'pertanyaan' => 'Penurunan pelanggaran disiplin pegawai',
                'penjelasan' => 'Persentase pernurunan pelanggaran disiplin pegawai diperoleh dari Jumlah pelanggaran tahun sebelumnya dikurangi Jumlah pelanggaran tahun ini kemudian dibagi dengan Jumlah pelanggaran tahun sebelumnya',
                'tipe_jawaban' => 'angka',
                'pilihan_jawaban' => json_encode([]),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 35: Meningkatnya capaian kinerja unit kerja
            [
                'indikator_id' => 35,
                'kode' => 'a',
                'pertanyaan' => 'Persentase Sasaran dengan capaian 100% atau lebih',
                'penjelasan' => 'Persentase diperoleh dari Jumlah Sasaran Kinerja yang tercapai 100% atau lebih dibagi dengan Jumlah Sasaran Kinerja',
                'tipe_jawaban' => 'angka',
                'pilihan_jawaban' => json_encode([]),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 36: Pemberian Reward and Punishment
            [
                'indikator_id' => 36,
                'kode' => 'a',
                'pertanyaan' => 'Hasil Capaian/Monitoring Perjanjian Kinerja telah dijadikan dasar sebagai pemberian reward and punishment bagi organisasi',
                'penjelasan' => 'a. Seluruh capaian kinerja (Perjanjian Kinerja) merupakan unsur dalam pemberian reward and punishment b. Sebagian besar Capaian Kinerja (lebih dari 50% Perjanjian kinerja) merupakan unsur dalam pemberian reward and punishment c. Sebagian kecil Capaian Kinerja (kurang dari 50% Perjanjian kinerja) merupakan unsur dalam pemberian reward and punishment d. Capaian Kinerja (Perjanjian kinerja) belum menjadi unsur dalam pemberian reward and punishment',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 37: Kerangka Logis Kinerja
            [
                'indikator_id' => 37,
                'kode' => 'a',
                'pertanyaan' => 'Apakah terdapat penjenjangan kinerja ((Kerangka Logis Kinerja) yang mengacu pada kinerja utama organisasi dan dijadikan dalam penentuan kinerja seluruh pegawai?',
                'penjelasan' => 'a. terdapat Kerangka Logis kinerja yang mengacu pada kinerja utama organisasi dan digunakan dalam penjabaran kinerja seluruh pegawai b. terdapat Kerangka Logis kinerja yang mengacu pada kinerja utama organisasi namun belum digunakan dalam penjabaran kinerja seluruh pegawai c. Kerangka Logis kinerja ada namun belum mengacu pada kinerja utama organisasi dan belum digunakan dalam penjabaran kinerja seluruh pegawai d. Kerangka Logis kinerja belum ada',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 38: Mekanisme Pengendalian
            [
                'indikator_id' => 38,
                'kode' => 'a',
                'pertanyaan' => 'Telah dilakukan mekanisme pengendalian aktivitas secara berjenjang',
                'penjelasan' => 'a. Terdapat pengendalian aktivitas utama organisasi yang tersistem mulai dari perencanaan, penilaian risiko, pelaksanaan, monitoring, dan pelaporan oleh penanggung jawab aktivitas serta pimpinan unit kerja dan telah menghasilkan peningkatan kinerja, mekanise kerja baru yang lebih efektif, efisien, dan terkendali b. Terdapat pengendalian aktivitas utama organisasi yang tersistem mulai dari perencanaan, penilaian risiko, pelaksanaan, monitoring, dan pelaporan oleh penanggung jawab aktivitas serta pimpinan unit kerja namun belum berdampak pada peningkatan kinerja unit kerja c.Terdapat pengendalian aktivitas utama organisasi yang tersistem mulai dari perencanaan, penilaian risiko, pelaksanaan, monitoring, dan pelaporan oleh penanggung jawab aktivitas d. Terdapat pengendalian aktivitas utama organisasi tetapi tidak tersistem e. Tidak terdapat pengendalian atas aktivitas utama organisasi',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D', 'E']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 39: Penanganan Pengaduan Masyarakat
            [
                'indikator_id' => 39,
                'kode' => 'a',
                'pertanyaan' => 'Persentase penanganan pengaduan masyarakat',
                'penjelasan' => 'Penilaian ini menghitung realisasi penanganan pengaduan masyarakat yang harus diselesaikan',
                'tipe_jawaban' => 'angka',
                'pilihan_jawaban' => json_encode([]),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 40: Penyampaian Laporan Harta Kekayaan
            [
                'indikator_id' => 40,
                'kode' => 'a',
                'pertanyaan' => 'Persentase penyampaian LHKPN',
                'penjelasan' => 'Kewajiban Penyelenggara Negara untuk melaporkan harta kekayaan diatur dalam: 1. Undang-Undang No. 28 Tahun 1999 2. Undang-Undang No. 30 Tahun 2002 3. Undang-Undang No. 10 Tahun 2015 4. Peraturan Komisi Pemberantasan Korupsi No. 07 Tahun 2016 5. Instruksi Presiden No. 5 Tahun 2004 6. SE MenPANRB No. SE/03/M.PAN/01/2005',
                'tipe_jawaban' => 'angka',
                'pilihan_jawaban' => json_encode([]),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 41: Upaya dan/atau Inovasi Pelayanan Publik
            [
                'indikator_id' => 41,
                'kode' => 'a',
                'pertanyaan' => 'Upaya dan/atau inovasi telah mendorong perbaikan pelayanan publik pada: 1. Kesesuaian Persyaratan 2. Kemudahan Sistem, Mekanisme, dan Prosedur 3. Kecepatan Waktu Penyelesaian 4. Kejelasan Biaya/Tarif, Gratis 5. Kualitas Produk Spesifikasi Jenis Pelayanan 6. Kompetensi Pelaksana/Web 7. Perilaku Pelaksana/Web 8. Kualitas Sarana dan prasarana 9. Penanganan Pengaduan, Saran dan Masukan',
                'penjelasan' => 'a. Upaya dan/atau inovasi yang dilakukan telah mendorong perbaikan seluruh pelayanan publik yang prima (lebih Cepat dan mudah) b. Upaya dan/atau inovasi yang dilakukan belum seluruhnya memberikan dampak pada perbaikan pelayanan publik yang prima (Cepat dan mudah) c. Upaya dan/atau inovasi yang dilakukan belum sesuai kebutuhan d. Belum ada inovasi',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'indikator_id' => 41,
                'kode' => 'b',
                'pertanyaan' => 'Upaya dan/atau inovasi pada perijinan/pelayanan telah dipermudah: 1. Waktu lebih cepat 2. Pelayanan Publik yang terpadu 3. Alur lebih pendek/singkat 4 Terintegrasi dengan aplikasi',
                'penjelasan' => 'Persentase diperoleh dari Jumlah perijinan/pelayanan yang telah dipermudah dibagi dengan Jumlah perijinan/pelayanan yang terdata/terdaftar',
                'tipe_jawaban' => 'angka',
                'pilihan_jawaban' => json_encode([]),
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indikator 42: Penanganan Pengaduan Pelayanan dan Konsultasi
            [
                'indikator_id' => 42,
                'kode' => 'a',
                'pertanyaan' => 'Penanganan pengaduan pelayanan dilakukan melalui berbagai kanal/media secara responsive dan bertanggung jawab',
                'penjelasan' => 'a. Pengaduan pelayanan dan konsultasi telah direspon dengan cepat melalui berbagai kanal/media b. Pengaduan pelayanan dan konsultasi telah direspon dengan cepat melalui kanal/media yang terbatas c. Pengaduan pelayanan dan konsultasi direspon lambat melalui berbagai kanal/media d. Pengaduan pelayanan dan konsultasi direspon lambat dan kanal/media terbatas',
                'tipe_jawaban' => 'pilihan_ganda',
                'pilihan_jawaban' => json_encode(['A', 'B', 'C', 'D']),
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('tm_pertanyaan')->insert($pertanyaans);
    }
}
