<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubPertanyaanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Hapus data lama terlebih dahulu dengan disable foreign key check
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('tm_sub_pertanyaan')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $subPertanyaans = [
            [
                'id' => 1,
                'periode_id' => null,
                'pertanyaan_id' => 88,
                'kode' => 'a',
                'pertanyaan' => 'Jumlah Agen Perubahan',
                'penjelasan' => null,
                'tipe_input' => 'jumlah',
                'satuan' => 'Jumlah',
                'formula' => null,
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'periode_id' => null,
                'pertanyaan_id' => 88,
                'kode' => 'b',
                'pertanyaan' => 'Jumlah Perubahan yang dibuat',
                'penjelasan' => null,
                'tipe_input' => 'jumlah',
                'satuan' => 'Jumlah',
                'formula' => null,
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'periode_id' => null,
                'pertanyaan_id' => 89,
                'kode' => 'a',
                'pertanyaan' => 'Jumlah Perubahan yang dibuat',
                'penjelasan' => null,
                'tipe_input' => 'jumlah',
                'satuan' => 'Jumlah',
                'formula' => null,
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'periode_id' => null,
                'pertanyaan_id' => 89,
                'kode' => 'b',
                'pertanyaan' => 'Jumlah Perubahan yang telah diintegrasikan dalam sistem manajemen',
                'penjelasan' => null,
                'tipe_input' => 'jumlah',
                'satuan' => 'Jumlah',
                'formula' => null,
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'periode_id' => null,
                'pertanyaan_id' => 100,
                'kode' => 'a',
                'pertanyaan' => 'Jumlah pelanggaran tahun sebelumnya',
                'penjelasan' => null,
                'tipe_input' => 'jumlah',
                'satuan' => 'Jumlah',
                'formula' => null,
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'periode_id' => null,
                'pertanyaan_id' => 100,
                'kode' => 'b',
                'pertanyaan' => 'Jumlah pelanggaran tahun ini',
                'penjelasan' => null,
                'tipe_input' => 'jumlah',
                'satuan' => 'Jumlah',
                'formula' => null,
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'periode_id' => null,
                'pertanyaan_id' => 100,
                'kode' => 'c',
                'pertanyaan' => 'Jumlah pelanggaran yang telah diberikan sanksi/hukuman',
                'penjelasan' => null,
                'tipe_input' => 'jumlah',
                'satuan' => 'Jumlah',
                'formula' => null,
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'periode_id' => null,
                'pertanyaan_id' => 101,
                'kode' => 'a',
                'pertanyaan' => 'Jumlah Sasaran Kinerja',
                'penjelasan' => null,
                'tipe_input' => 'jumlah',
                'satuan' => 'Jumlah',
                'formula' => null,
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'periode_id' => null,
                'pertanyaan_id' => 101,
                'kode' => 'b',
                'pertanyaan' => 'Jumlah Sasaran Kinerja yang tercapai 100% atau lebih',
                'penjelasan' => null,
                'tipe_input' => 'jumlah',
                'satuan' => 'Jumlah',
                'formula' => null,
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'periode_id' => null,
                'pertanyaan_id' => 105,
                'kode' => 'a',
                'pertanyaan' => 'Jumlah pengaduan masyarakat yang harus ditindaklanjuti',
                'penjelasan' => null,
                'tipe_input' => 'jumlah',
                'satuan' => 'Jumlah',
                'formula' => null,
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'periode_id' => null,
                'pertanyaan_id' => 105,
                'kode' => 'b',
                'pertanyaan' => 'Jumlah pengaduan masyarakat yang sedang diproses',
                'penjelasan' => null,
                'tipe_input' => 'jumlah',
                'satuan' => 'Jumlah',
                'formula' => null,
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'periode_id' => null,
                'pertanyaan_id' => 105,
                'kode' => 'c',
                'pertanyaan' => 'Jumlah pengaduan masyarakat yang selesai ditindaklanjuti',
                'penjelasan' => null,
                'tipe_input' => 'jumlah',
                'satuan' => 'Jumlah',
                'formula' => null,
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'periode_id' => null,
                'pertanyaan_id' => 106,
                'kode' => 'a',
                'pertanyaan' => 'Jumlah yang harus melaporkan',
                'penjelasan' => 'Perhitungan: Kepala satuan kerja + Pejabat yang diwajibkan menyampaikan LHKPN + Lainnya',
                'tipe_input' => 'jumlah',
                'satuan' => 'Jumlah',
                'formula' => '=K179+K180+K181',
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'periode_id' => null,
                'pertanyaan_id' => 106,
                'kode' => 'b',
                'pertanyaan' => 'Jumlah Kepala satuan kerja yang harus melaporkan',
                'penjelasan' => null,
                'tipe_input' => 'jumlah',
                'satuan' => 'Jumlah',
                'formula' => null,
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'periode_id' => null,
                'pertanyaan_id' => 106,
                'kode' => 'c',
                'pertanyaan' => 'Jumlah Pejabat yang diwajibkan menyampaikan LHKPN',
                'penjelasan' => null,
                'tipe_input' => 'jumlah',
                'satuan' => 'Jumlah',
                'formula' => null,
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'periode_id' => null,
                'pertanyaan_id' => 106,
                'kode' => 'd',
                'pertanyaan' => 'Jumlah Lainnya',
                'penjelasan' => null,
                'tipe_input' => 'jumlah',
                'satuan' => 'Jumlah',
                'formula' => null,
                'urutan' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'periode_id' => null,
                'pertanyaan_id' => 106,
                'kode' => 'e',
                'pertanyaan' => 'Jumlah Lainnya yang sudah melaporkan',
                'penjelasan' => null,
                'tipe_input' => 'jumlah',
                'satuan' => 'Jumlah',
                'formula' => null,
                'urutan' => 5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'periode_id' => null,
                'pertanyaan_id' => 108,
                'kode' => 'a',
                'pertanyaan' => 'Jumlah perijinan/pelayanan yang terdata/terdaftar',
                'penjelasan' => null,
                'tipe_input' => 'jumlah',
                'satuan' => 'Jumlah',
                'formula' => null,
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'periode_id' => null,
                'pertanyaan_id' => 108,
                'kode' => 'b',
                'pertanyaan' => 'Jumlah perijinan/pelayanan yang telah dipermudah',
                'penjelasan' => null,
                'tipe_input' => 'jumlah',
                'satuan' => 'Jumlah',
                'formula' => null,
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'periode_id' => null,
                'pertanyaan_id' => 113,
                'kode' => 'a',
                'pertanyaan' => 'Jumlah yang harus melaporkan',
                'penjelasan' => 'Perhitungan: Kepala satuan kerja + Pejabat yang diwajibkan menyampaikan LHKPN + Lainnya',
                'tipe_input' => 'jumlah',
                'satuan' => 'Jumlah',
                'formula' => '=K179+K180+K181',
                'urutan' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'periode_id' => null,
                'pertanyaan_id' => 113,
                'kode' => 'b',
                'pertanyaan' => 'Jumlah Pejabat administrator (eselon III) yang harus menyampaikan Non LHKPN',
                'penjelasan' => null,
                'tipe_input' => 'jumlah',
                'satuan' => 'Jumlah',
                'formula' => null,
                'urutan' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'periode_id' => null,
                'pertanyaan_id' => 113,
                'kode' => 'c',
                'pertanyaan' => 'Jumlah Pejabat Penawas (eselon IV) yang harus menyampaikan Non LHKPN',
                'penjelasan' => null,
                'tipe_input' => 'jumlah',
                'satuan' => 'Jumlah',
                'formula' => null,
                'urutan' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'periode_id' => null,
                'pertanyaan_id' => 113,
                'kode' => 'd',
                'pertanyaan' => 'Jumlah Fungsional dan Pelaksana yang harus menyampaikan Non LHKPN',
                'penjelasan' => null,
                'tipe_input' => 'jumlah',
                'satuan' => 'Jumlah',
                'formula' => null,
                'urutan' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'periode_id' => null,
                'pertanyaan_id' => 113,
                'kode' => 'e',
                'pertanyaan' => 'Jumlah Total yang sudah melaporkan Non LHKPN',
                'penjelasan' => null,
                'tipe_input' => 'jumlah',
                'satuan' => 'Jumlah',
                'formula' => null,
                'urutan' => 5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('tm_sub_pertanyaan')->insert($subPertanyaans);
    }
}
